# #####################################################################
# Automatically generated by qmake (2.01a) Fri Jan 22 17:42:55 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    gui \
    resources
INCLUDEPATH += . \
    gui

# Input
HEADERS += gui/playerframe.h \
    player.h \
    square.h \
    card.h
FORMS += monopoly.ui
SOURCES += main.cpp \
    gui/playerframe.cpp
RESOURCES += resources/resources.qrc
